name: Deploy Application

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - stage
          - prod

      image_tag:
        description: "Docker image tag"
        required: true
        default: "latest"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Print Inputs
        run: |
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Image Tag: ${{ github.event.inputs.image_tag }}"

      - name: Deploy Application
        run: |
          echo "Deploying application to ${{ github.event.inputs.environment }}"
          echo "Using image tag ${{ github.event.inputs.image_tag }}"