name: Concurrency Pipeline
on: push
concurrency:
  group: build-group
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Application
        run: echo "Building application..."
        run: sleep 20