name: Checkout Demo-Example
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: List files
        run: ls -l