name: Pull Request Pipeline
on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: echo "Installing dependencies"

      - name: Run Tests
        run: echo "Running unit tests"